Add functionality to the Reservation screen
BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda pull request #18
Opened 2023-07-05 01:03 UTC by Axw3ll

In this issue, we added functionality to the FlatList component to be able to view the flights stored in the database. We achieved this by querying Firebase and specifying that we wanted the data related to the current user's ID. We used the useEffect hook to ensure that the query is only executed once and not on every render.

# Description
-Introduces the GetFlights function which retrieves flights for the current user. It uses Firestore and Authentication from  Firebase. It imports necessary modules, defines GetFlights as an async function, fetches the current user, queries the 'flights' Firestore collection filtered by user's UID, retrieves the matching flights, and stores them in an array. It then logs and returns the flights array. Errors during execution are logged and rethrown.

## Screenshots
![imagen](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/88905195/50b3561b-9e75-4cc2-82ea-b7336053a779)

![imagen](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/88905195/7bde0001-02bc-4627-9d8e-d36e3e7994ff)

2023-07-05 01:34 UTC, Eduardoespl approved these changes
LGTM! 🚀

2023-07-05 01:34 UTC, Lizzflores approved these changes
LGTM!👍

2023-07-05 22:10 UTC, xFerchoVJ reviewed
LGTM, just remove the comments :)

2023-07-05 22:10 UTC, xFerchoVJ commented on src/components/Card.jsx
> +//passengers
Try not to leave comments on your PR

2023-07-05 22:27 UTC, BrandonVG commented on src/components/Card.jsx
> +//passengers
We deleted the comments

2023-07-06 00:20 UTC, YilKanda requested changes

2023-07-06 00:20 UTC, YilKanda commented on src/components/Card.jsx
>  }
Check the indentation of your file

2023-07-06 00:20 UTC, YilKanda commented on src/components/Card.jsx
>          width:'40%',
The styles must be in a separate file.

2023-07-06 00:20 UTC, YilKanda commented on src/components/FlightList.jsx
> +    },[]);
Check the indentation

2023-07-06 00:20 UTC, YilKanda commented on src/hooks/GetFlights.js
> +    console.log(flights);
Don't leave debug code on GitHub, like console.log(), you can use Alert.alert() instead

2023-07-06 00:20 UTC, YilKanda commented on src/hooks/GetFlights.js
> +    console.log(error);
Don't leave debug code on GitHub, like console.log(), you can use Alert.alert() instead

2023-07-06 00:20 UTC, YilKanda commented on src/screens/HomeScreen.jsx
>      console.log('handleOnLogOut executed');
Don't leave debug code on GitHub, like console.log(), you can use Alert.alert() instead

2023-07-06 23:21 UTC, merged