Sprint 4/issue 21#add functionality for users to add new flight reservations and implement storage in firebase
BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda pull request #22
Opened 2023-07-14 01:11 UTC by Tole15

Successful Implementation of Flight Reservation Data, Autocomplete Picker and Data Storage

This update signifies the completion and successful operation of the flight reservation country data autocomplete picker feature along with the seamless storage of reservation information. The autocomplete picker has been integrated into the system, offering users an enhanced booking experience by simplifying the input of the country details and flight preferences. It intelligently suggests options as users type, making the process quicker and more convenient.

Furthermore, the implementation of data storage functionality ensures that users' flight reservation details are securely saved and readily accessible. By securely storing this information, users can easily manage their bookings, retrieve important details, and have a hassle-free travel planning experience.

Both the autocomplete picker and the reservation data storage are now fully operational, providing users with a comprehensive and efficient flight reservation system. These updates significantly enhance the overall user experience and contribute to a seamless and reliable flight booking process.

## Screenshots
![Screenshot_1689296365](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/a6a4fe8c-9875-4071-808f-c319570b16c7)
![Screenshot_1689296370](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/62542a3f-cec7-4b42-ac82-0d2ce470a720)
![Screenshot_1689296373](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/6cb0cbbd-83cf-4422-b568-df4a83fdccd3)
![Screenshot_1689296414](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/25dc8ab5-144c-4adc-8bd6-49ae168d6541)
![Screenshot_1689296417](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/9cbdfb8c-7bf8-4afd-a3eb-2601c457a01d)
![Screenshot_1689296359](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-equipo-alfa-buena-maravilla-onda/assets/129608820/cc0f66b0-41a9-4941-9d19-2570a3a24fc1)

2023-07-14 01:56 UTC, IvanCa27 approved these changes
### _**Good job, guys**_

2023-07-14 02:20 UTC, Eduardoespl reviewed
Good Job, lgtm!

2023-07-14 02:20 UTC, Eduardoespl approved these changes

2023-07-17 13:11 UTC, YilKanda requested changes

2023-07-17 13:11 UTC, YilKanda commented on src/components/BackHeaderButton.jsx
> +        color="#5974f5"
If you have a color library, you can use it here as well.

2023-07-17 13:11 UTC, YilKanda commented on src/components/BookingInput.jsx
> +        rightButtonsContainerStyle={{backgroundColor: '#FFFFFF'}}
If you have a color library, you can use it here as well.

2023-07-17 13:11 UTC, YilKanda commented on src/components/DatePickerCalendar.jsx
> +          selectedTextColor: '#fff',
If you have a color library, you can use it here as well.

The styles must go in an external file.

2023-07-17 13:11 UTC, YilKanda commented on src/data/Flights.json
> +}
Add a blank line

2023-07-17 13:11 UTC, YilKanda commented on src/hooks/HandleLogin.js
> +    console.log('Invalid email format');
Do not leave debug code in production. You can use Alert.alert() instead.

2023-07-17 13:11 UTC, YilKanda commented on src/hooks/HandleLogin.js
> +    console.log('Incorrect email and/or password');
Do not leave debug code in production. You can use Alert.alert() instead.

2023-07-17 13:11 UTC, YilKanda commented on src/hooks/SetFlights.js
> +    console.error('Error al agregar los valores a Firestore:', error);
Do not leave debug code in production. You can use Alert.alert() instead.

2023-07-17 13:11 UTC, YilKanda commented on src/screens/Booking.jsx
> +          console.error(error);
Do not leave debug code in production.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/AddButtonStyles.js
> +    backgroundColor: '#5974f5',
If you have a color library use it.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/BookingInputStyles.js
>      borderBottomColor: '#bcbcbc',
If you have a color library use it.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/BookingStyles.js
> +    backgroundColor: 'white',
If you have a color library use it.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/NextButtonStyles.js
> +    shadowRadius: 2,
Sort the styles alphabetically.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/NextButtonStyles.js
> +    color: '#fbfbfc',
If you have a color library, use it.

2023-07-17 13:11 UTC, YilKanda commented on src/styles/NextButtonStyles.js
> +    fontWeight: 'bold',
Sort your styles alphabetically

2023-07-19 01:17 UTC, merged